### ISSUE TITLE
IndexError: list index out of range程序运行出错

### ISSUE THREAD

**Issue by Cuihaoisme** [shartoo/luna16_multi_size_3dcnn#20]
![image](https://user-images.githubusercontent.com/32264420/56938994-1bc8dd00-6b38-11e9-82a8-70cb2eff0069.png)

Traceback (most recent call last):
  File "/home/ch/luna_1/luna16_multi_size_3dcnn/data_prepare.py", line 267, in get_test_batch
    arr = np.load(npy)
  File "/root/Anaconda/lib/python3.6/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    model.inference(normalazation_output_path,test_path,0,True)
  File "/home/ch/luna_1/luna16_multi_size_3dcnn/model.py", line 178, in inference
    test_batch,test_label = get_test_batch(test_path)
  File "/home/ch/luna_1/luna16_multi_size_3dcnn/data_prepare.py", line 278, in get_test_batch
    batch_array.append(batch_array[-1])  # some nodule process error leading nonexistent of the file, using the last file copy to fill
不知道什么原因，望解答！

**Comment by shartoo** [comment]
可能是你传入的路径有问题，你调试或者打印你传入的路径列表试试。
