### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by qiuliwang** [shartoo/luna16_multi_size_3dcnn#5]
这是个很棒的项目，处理数据的部分没有太大问题就跑出来了，但是在训练过程中出现了一下问题：
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    model.inference(normalazation_output_path,test_path,0,True)
  File "/home/wangqiuli/Documents/luna16_multi_size_3dcnn/model.py", line 145, in inference
    _,summary = sess.run([train_step, merged],feed_dict =feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1104, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
请问作者能否帮忙解答一下

**Comment by 516936971** [comment]
我也遇到了这个问题，作者能否帮忙解答一下呢？

**Comment by shartoo** [comment]
可否检查下数据呢？ 我这边没有出现这个问题。这个错误的意思是 赋值有问题

**Comment by zp678** [comment]
我也遇到同样的问题，请问大家解决了没有，可否帮忙解答一下？万分感谢

**Comment by zp678** [comment]
@shartoo ,请问作者，测试数据和训练数据的维度是否是一样的，都是4维？

**Comment by zp678** [comment]
好的，谢谢您

2018-07-30 10:28 GMT+08:00 WangQL <notifications@github.com>:

**Comment by Johnhave** [comment]
请问大家这个问题解决了吗？

**Comment by wangqiuli0102** [comment]
> 请问大家这个问题解决了吗？

测试单个尺度就行了
